rust-cross: Download pre-built rust-std crate from https://static.rust-lang.org/dist/
meta-rust can't build firefox-60esr:

 * https://github.com/OSSystems/meta-browser/pull/128
 * https://github.com/OSSystems/meta-browser/pull/160

due to missing rust-std crate for the target:

  |  0:03.44 DEBUG: | error[E0463]: can't find crate for `std`
  |  0:03.44 DEBUG: |   |
  |  0:03.44 DEBUG: |   = note: the `x86_64-unknown-linux-gnu` target may not be installed

This commit is a dirty hack to resolve this problem by using pre-built
rust-std:

  * https://static.rust-lang.org/dist/

Since their build ID doesn't match with the rustc which is built by
meta-rust, they can't use it as-is:

  0:02.89 DEBUG: | error[E0514]: found crate `std` compiled by an incompatible version of rustc
  0:02.89 DEBUG: |   |
  0:02.89 DEBUG: |   = help: please recompile that crate using this compiler (rustc 1.27.1)
  0:02.89 DEBUG: |   = note: the following crate versions were found:
  0:02.89 DEBUG: |           crate `std` compiled by rustc 1.27.1 (5f2b325f6 2018-07-07): /home/aho/Yocto/master/build/tmp/work/core2-64-poky-linux/firefox/60.1.0esr-r0/recipe-sysroot-native/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_unicode-99a0af7f5e9f8d8d.rlib
  0:02.89 DEBUG: |           crate `std` compiled by rustc 1.27.1 (5f2b325f6 2018-07-07): /home/aho/Yocto/master/build/tmp/work/core2-64-poky-linux/firefox/60.1.0esr-r0/recipe-sysroot-native/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0888da25bc5aa659.rlib
  0:02.89 DEBUG: |           crate `std` compiled by rustc 1.27.1 (5f2b325f6 2018-07-07): /home/aho/Yocto/master/build/tmp/work/core2-64-poky-linux/firefox/60.1.0esr-r0/recipe-sysroot-native/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-0888da25bc5aa659.so

To avoid it, this commit also includes a patch to skip checking build
ID.